/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ButtonCvaRouteImport } from './routes/button-cva'
import { Route as ButtonCnRouteImport } from './routes/button-cn'
import { Route as IndexRouteImport } from './routes/index'

const ButtonCvaRoute = ButtonCvaRouteImport.update({
  id: '/button-cva',
  path: '/button-cva',
  getParentRoute: () => rootRouteImport,
} as any)
const ButtonCnRoute = ButtonCnRouteImport.update({
  id: '/button-cn',
  path: '/button-cn',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/button-cn': typeof ButtonCnRoute
  '/button-cva': typeof ButtonCvaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/button-cn': typeof ButtonCnRoute
  '/button-cva': typeof ButtonCvaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/button-cn': typeof ButtonCnRoute
  '/button-cva': typeof ButtonCvaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/button-cn' | '/button-cva'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/button-cn' | '/button-cva'
  id: '__root__' | '/' | '/button-cn' | '/button-cva'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ButtonCnRoute: typeof ButtonCnRoute
  ButtonCvaRoute: typeof ButtonCvaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/button-cva': {
      id: '/button-cva'
      path: '/button-cva'
      fullPath: '/button-cva'
      preLoaderRoute: typeof ButtonCvaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/button-cn': {
      id: '/button-cn'
      path: '/button-cn'
      fullPath: '/button-cn'
      preLoaderRoute: typeof ButtonCnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ButtonCnRoute: ButtonCnRoute,
  ButtonCvaRoute: ButtonCvaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
